services:
  - type: web
    name: fingerprint-check-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: worker
    name: aerolink-telegram-bot
    env: python
    rootDir: telegram-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: AEROLINK_API_KEY
        value: aero_live_uQ0EFYU54Nw_dpXMCCJ4M3GIHIuvxj_DqutYkLyUCYA
      - key: TELEGRAM_TOKEN
        value: 8661760698:AAGobvipmg_0eW4FDx2rbk7t2AQ31jznvNs
      - key: PYTHON_VERSION
        value: "3.11.0"
